apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fluxcd
  namespace: default
spec:
  interval: 15m
  path: "./fluxcd/deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: fluxcd
