apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: fluxcd
  labels:
    app: fluxcd
spec:
  type: ClusterIP
  selector:
    app: fluxcd
  ports:
    - port: 80
      protocol: TCP
      name: http
      targetPort: 5000